arch: 
  - ppc64le
dist: focal
language: java
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
git:
  depth: 3
  quiet: true
  submodules: false
script:
  - echo "Hello World!"
  - arch
  - java --version
  - ls -ltr
